language: java
sudo: required

install:
  - ./gradlew -v

services:
- docker

jobs:
  include:
    - name: check code
      jdk: openjdk17
      dist: xenial
      script: ./gradlew clean checkstyle licenseMain licenseTest webapp --daemon
    - jdk: openjdk17
      dist: focal
      script: ./gradlew clean assemble --no-daemon

env:
  - CI=false

before_deploy:
- echo "build start... sylph"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
